HackSC/hibiscus

README.md
=> adding last line to readme describing our intention

README.md, apps/dashboard/common/hackform.metadata.ts, apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx, apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx, apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx, apps/dashboard/components/hackerform/short-text-input/short-text-input.tsx, apps/dashboard/hooks/use-hackform/use-hackform.ts, apps/dashboard/store/hackform-slice.ts, apps/dashboard/store/store.ts, libs/types/src/lib/form.ts, libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx
=> implement multi-select

README.md, apps/dashboard/common/hackform.metadata.ts, apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx, apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx, apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx, apps/dashboard/components/hackerform/short-text-input/short-text-input.tsx, apps/dashboard/hooks/use-hackform/use-hackform.ts, apps/dashboard/store/hackform-slice.ts, apps/dashboard/store/store.ts, libs/types/src/lib/form.ts, libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx
- add all questions into hackform (yet to add dynamically-fetched searchable options for questions like schools or majors)
- #283
- fix problem consecutive questions with same type share same state (sol: add `key` prop to distinguish them per this article https://beta.reactjs.org/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key)
=> Hib 68 add all questions into hackform

apps/dashboard/common/api.ts, apps/dashboard/common/hackform.metadata.ts, apps/dashboard/common/schools.ts, apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx, apps/dashboard/components/hackerform/hackform-introduction/hackform-introduction.tsx, apps/dashboard/components/hackerform/hackform-question-header/hackform-question-header.tsx, apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx, apps/dashboard/components/hackerform/hackform/hackform.tsx, apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx, apps/dashboard/components/hackerform/other-field.tsx, apps/dashboard/components/hackerform/question-creator/question-creator.tsx, apps/dashboard/components/hackerform/searchable-options-input/searchable-options-input.tsx, apps/dashboard/components/hackerform/single-choice-input/single-choice-input.tsx, apps/dashboard/hooks/use-hackform/use-hackform.ts, apps/dashboard/pages/api/schools.ts, apps/dashboard/store/hackform-slice.ts, assets/schools.csv, libs/types/src/lib/form.ts, libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx, libs/ui-kit-2023/src/lib/searchable-option-select-input/searchable-option-select-input.tsx
=> add schools and majors

apps/sso/pages/login/index.tsx, libs/sso-client/src/lib/sso-client.ts
- Perform null check on callback URL
=> Fix 405 error on login

apps/dashboard/components/portal-menu/portal-menu.tsx, apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts, apps/dashboard/layouts/portal-layout.tsx, apps/dashboard/pages/index.tsx, libs/env/src/index.ts
- Reduced database calls from 3 times to 1 time per page load
- Fixed broken env variable names in hibiscus/env
=> Reduce supabase database queries on dashboard

apps/dashboard/middleware.ts, apps/dashboard/pages/404/index.tsx, apps/dashboard/pages/apply-2023/index.tsx
- Unguard /api/schools
- Fix apply and 404 pages not rendering
=> Fix blocked schools endpoint on dashboard

libs/hibiscus-supabase-client/src/index.ts, supabase/migrations/20230109020457_add_email_and_profile_rls.sql
- Make email field in user_profile nullable
=> Fix database migrations

apps/interim/pages/sp23-diagrams/index.tsx
=> add redirect to /sp23-diagrams

apps/dashboard/common/hackform.metadata.tsx, apps/dashboard/common/schools.ts, apps/dashboard/components/hackerform/hackform-question-header/hackform-question-header.tsx, apps/dashboard/components/hackerform/searchable-options-question/searchable-options-question.tsx, apps/dashboard/pages/api/schools.ts, apps/dashboard/pages/apply-2023/index.tsx, libs/types/src/lib/form.ts
- closes HIB-114, HIB-116, HIB-117, HIB-118, HIB-119
i.e:
- add "Are you looking for a job"
- ethnicity question improvements (hispanic → hispanic/latino, make it multi-select instead)
- make major question a dropdown
- Add USC next to USC dropdown in school question (it actually doesn't work as you wanted you have to type "(USC)" instead of just "USC"; we might find a way to work around this but IMO not worth the effort)
- Dropdown for graduation date
- closes HIB-115: add "loading" screen when user not loaded instead of incorrect "You have already applied" 
=> improvements to hackform

apps/dashboard/middleware.ts, apps/sso/middleware.ts, apps/sso/pages/api/unauthorized.ts, libs/sso-client/src/lib/sso-client.ts
- Check for cookies on middleware before allowing access to API endpoints
=> SSO Guard API paths

apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx, apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx, apps/dashboard/components/hackerform/long-text-question/long-text-question.tsx, apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx, apps/dashboard/components/hackerform/other-field.tsx, apps/dashboard/components/hackerform/question-creator/question-creator.tsx, apps/dashboard/components/hackerform/single-choice-input/single-choice-input.tsx, apps/dashboard/pages/index.tsx, libs/ui-kit-2023/src/lib/date-picker/date-picker.tsx, libs/ui-kit-2023/src/lib/searchable-option-select-input/searchable-option-select-input.tsx
- Add responsiveness to Hackform
- Restyle Hackform components
=> hackform responsiveness

apps/sso/components/verify-card/verify-card.tsx
- Replace resend confirmation email link with message
=> Replace resend confirmation email link with message

apps/dashboard/components/hacker-portal/hacker-portal.tsx, apps/dashboard/pages/index.tsx, apps/sso/components/login-card/login-card.tsx, apps/sso/components/otp-input/otp-input.spec.tsx, apps/sso/components/otp-input/otp-input.tsx, apps/sso/components/reset-card/reset-card.tsx, apps/sso/components/reset-card/reset-email-card.tsx, apps/sso/components/signup-card/signup-card.tsx, apps/sso/components/verify-card/verify-card.tsx, package.json, yarn.lock
- Add loading effect to login, signup, verify
- Change cursor to pointer when user hover over verify otp button
- Press Enter in verify otp will trigger verifying opt
- Add more responsiveness to login, signup, verify, and hacker portal
=> Hib 126 polish sso

apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.ts, apps/pointr/pages/index.tsx, apps/sso/components/verify-card/verify-card.tsx, libs/types/src/lib/supabase.gen.ts
=> redirect hack.sc to hacksc.com

apps/dashboard/components/hacker-portal/hacker-portal.tsx, apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx, apps/sso/components/login-card/login-card.tsx, apps/sso/components/signup-card/signup-card.tsx, apps/sso/components/verify-card/verify-card.tsx
- Change logic in hacker portal to check for application status instead of app_id to verify if a hacker has submitted an application
- Add code to change application status to "IN_REVIEW" when a hacker submit the application in hackerform-end
=> fix application status logic

supabase/migrations/20230119083157_add_application_statuses.sql
=> add application status fill

apps/dashboard/store/menu-slice.ts
=> defer team service

apps/dashboard/common/hackform.metadata.tsx
- replacement for team service for now
=> team members field

amplify.yml
=> add amplify.yml

apps/dashboard/common/hackform.metadata.tsx, apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx, apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx
- last one needs to press button to submit
- number of questions remaining
=> quick fix for ux

apps/www-2023/components/faqs/faqs.tsx
- Add more FQA questions and answers to the FAQ section
=> add additional FQA questions

apps/sso/components/login-guard.tsx, apps/sso/components/verify-card/verify-card.tsx, libs/hibiscus-supabase-client/src/index.ts, libs/types/src/lib/api/sso.ts
=> Fix token refresh (closes HIB-138)

apps/www-2023/components/speakers/speakers.tsx
=> fix speaker bio

apps/dashboard/components/hackerform/hackform-backnext-widget/hackform-backnext-widget.tsx, apps/dashboard/components/hackerform/hackform-question/hackform-question.tsx, apps/dashboard/components/hackerform/long-text-question/long-text-question.tsx, apps/dashboard/components/hackerform/multi-select-question/multi-select-question.tsx, apps/dashboard/components/hackerform/other-field.tsx, apps/dashboard/components/hackerform/question-creator/question-creator.tsx
- Fix hack-form responsiveness for mobile view
=> fix hackform responsiveness

apps/dashboard/common/hackform.metadata.tsx, apps/dashboard/pages/api/resume.ts
- for the favorite project question to 50 words
=> reduce word count

supabase/migrations/20230125064704_add_notes_and_edit_participants.sql
- Add participants and initial migration for notes.
=> Make changes for merge request.

apps/dashboard/common/mock-sponsor.ts, apps/dashboard/components/portal-menu/portal-menu.tsx, apps/dashboard/components/sponsor-portal/hacker-profile.tsx, apps/dashboard/components/sponsor-portal/hacker-tab.tsx, apps/dashboard/pages/sponsor-booth/index.tsx, apps/dashboard/store/menu-slice.ts, package.json, yarn.lock
- Create mock api for sponsor portal which contains a function to get all attendees
- Modify MenuState to include sponsorRoutes for portal menu to show appropriate  menu links for sponsor
- Modify portal-menu to show role based menu links
=> add mock sponsor api

apps/event-service/app.py
API for all events (sorted chronologically) for a certain day
=> Add api to get events by day

create-fake-user.ts, tools/scripts/create-fake-user.ts
- run using `npx ts-node tools/scripts/create-fake-user.ts`
=> Add script to create fake user

libs/sso-client/src/lib/sso-client.ts
- Change 1 line to force vercel redeploy with new env vars
=> Change MAX_AGE env variable to 1 week

.github/workflows/ci.yml, .gitignore, apps/dashboard/components/hackerform/hackform-end/hackform-end.tsx, apps/dashboard/middleware.ts, apps/dashboard/next.config.js, apps/dashboard/project.json, apps/dashboard/sentry.client.config.ts, apps/dashboard/sentry.edge.config.ts, apps/dashboard/sentry.properties, apps/dashboard/sentry.server.config.ts, package.json, yarn.lock
- for logging errors
- added Sentry env variables for releasing CI builds
=> add sentry to dashboard

CODEOWNERS
=> change codeowners

apps/www-2023/components/hero/hero.tsx
=> screen aspect ratio fix

apps/dashboard/components/hacker-portal/apps-closed-placeholder.tsx, apps/dashboard/components/hacker-portal/hacker-portal.tsx, apps/dashboard/components/hacker-portal/rejection-message.tsx, apps/dashboard/pages/apply-2023/index.tsx, apps/dashboard/pages/index.tsx, package.json, yarn.lock
[dashboard]
- apps closed messages and logic using Vercel's Edge Config
- rejected hacker message
=> apps closed logic on dashboard + hackform; rejection message

apps/www-2023/components/apply-now/apply-now.tsx
=> applications closed

apps/sso/components/reset-card/reset-card.tsx
=> reset password hidden

apps/dashboard/components/hacker-portal/apps-closed-placeholder.tsx, apps/dashboard/components/hacker-portal/congrats-message.tsx, apps/dashboard/components/hacker-portal/rejection-message.tsx, apps/dashboard/components/rsvp-form/rsvp-form.tsx, libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx
- changed label a bit
- redo Checkbox ReactNode for title
- DOB question on RSVP form fixes for better validation
=> enhancements for RSVP stuff

apps/sso/components/reset-card/reset-card.tsx, supabase/config.toml
- Fix reset email double confirmation bug
=> Fix reset email double confirmation bug

apps/dashboard/pages/api/notes.ts, apps/dashboard/repository/notes.repository.ts
- Add endpoints for getting and updating/inserting notes for attendees.
- Tested manually
=> Add implementation for notes api.

apps/dashboard/pages/api/company/[companyId]/[eventId].ts, apps/dashboard/repository/attendee.repository.ts
- Only implemented first 3 filters for now.
- Tested manually
=> Add filter functionality for only basic 3 filters.

apps/dashboard/common/parse-dob.ts, apps/dashboard/common/search-user.ts
- Parse both mm/dd/yyyy and yyyy-mm-ddTxxxxxxxxxx timestamps
=> Fix DoB parsing in ID portal

tools/scripts/create-user.ts
- Make create user script take in role as arg
- Also renamed the script to create-user.ts
- Added run instructions
=> Make create user script take in role as arg

apps/dashboard/pages/api/companies/[userId].ts, apps/dashboard/pages/api/company/[companyId].ts, apps/dashboard/pages/api/company/[companyId]/[eventId].ts, apps/dashboard/repository/attendee.repository.ts, apps/dashboard/repository/company.repository.ts, apps/dashboard/repository/user.repository.ts, supabase/migrations/20230203200634_bridge_user_profiles_to_company_id.sql
- Modified endpoint to getCompanyInfo to cut out target_graduations and target_majors
- Added endpoint to get company_id and event_id given sponsor's user_id
- Tested manually
=> Hib 157 modify company endpoints in sponsor

apps/dashboard/components/sponsor-portal/hacker-profile.tsx, apps/dashboard/components/sponsor-portal/sponsor-portal.tsx, apps/dashboard/pages/index.tsx
remove company configuration screen
- ...
=> fix sponsor portal

supabase/migrations/20230126033433_leaderboard_schema_migration.sql, supabase/migrations/20230204070815_battlepass-redos.sql
- moved leaderboard column stuff up
=> fix migration

supabase/migrations/20230204070815_battlepass-redos.sql
=> Hotfix migrations

apps/dashboard/common/utils.ts, apps/dashboard/components/sponsor-portal/hacker-profile.tsx, apps/dashboard/pages/api/company/[companyId]/[eventId].ts
- Hotfixed resume and embedded link inside of "Resume Link"
- Tested manually
=> Hot fixed resume support.

apps/dashboard/common/parse-dob.ts, apps/dashboard/pages/identity-portal/attendee-event-scan/index.tsx, apps/dashboard/pages/index.tsx
=> Fix excessive API calls

apps/dashboard/pages/index.tsx, apps/dashboard/repository/feature-flag.repository.ts, apps/dashboard/repository/mongo.client.ts
- OOPS
- Made HibiscusMongoClient to prevent re-constructing the client => connection overflow
=> Uncomment feature flags + MongoClient overflow connection fixes

apps/dashboard/components/battlepass/battlepass-page.tsx
=> updated battlepass ui

CHANGELOG.md
- added descriptions in changelog
=> add changelog for #437

apps/interim/components/navbar/desktop-navbar/desktop-navbar.tsx, apps/interim/components/navbar/mobile-navbar/mobile-navbar.tsx, apps/interim/components/team-contact-blurbs/team-contact-blurbs.tsx, apps/interim/components/thank-you-text/thank-you-text.tsx, apps/interim/pages/index.tsx
- Update interim page to prepare for deploying on www.hacksc.com again
=> Update interim page to post-2023 (CU-866a0b1n7)

.github/dependabot.yml
=> make Dependabot weekly to not be too verbose

CHANGELOG.md, apps/dashboard/pages/identity-portal/attendee-event-scan/index.tsx, libs/env/src/index.ts, libs/sso-client/src/lib/sso-client.ts
(What have been done/changed)
- Implement Supabase database listener for new check-ins
- Optimize database calls when initially fetching data
- Fix "Disable SSO" option crashing in dev
(How will we test the changes requested on this PR?)
[] Tested event check-in page locally
[] Tested locally with disable SSO option set to both true and false
=> Update ID portal API calls

.husky/pre-commit
- After linting, only re-add files that were already staged
=> Change pre-commit hook to only commit staged files

libs/hibiscus-supabase-client/src/index.ts
- Fix broken signups (right now user profiles aren't being created because they are being blocked by invalid permissions)
=> Remove set role when creating user (set default in DB instead)

.env.example, .gitignore, apps/dashboard/components/hacker-portal/hacker-portal.tsx, apps/dashboard/components/hackform-tally/hackform-tally.tsx, apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.tsx, apps/dashboard/middleware.ts, apps/dashboard/pages/apply-2023-x/index.tsx, apps/dashboard/pages/apply-2023-x/success/index.tsx, apps/dashboard/pages/index.tsx, apps/dashboard/store/menu-slice.ts, libs/env/src/index.ts, libs/sso-client/src/lib/sso-client.ts, supabase/migrations/20230828000000_app_id_not_uuid.sql
- Implement Tally integration for HackSC X applications
=> Implement Tally integration for HackSC X applications

apps/dashboard/hooks/use-hibiscus-user/use-hibiscus-user.tsx, apps/dashboard/pages/apply-2023-x/index.tsx, libs/types/src/lib/user.ts
- Prefill user names and email in Tally
=> Prefill user names and email in Tally

supabase/migrations/20231003190429_remote_schema.sql
=> Sync supabase migrations with remote

supabase/migrations/20231003190429_remote_schema.sql, supabase/migrations/20231003191442_revoke_write_access_for_app_status_and_role.sql
=> Update user_profiles access permissions, revoke write access for application status and role

.github/workflows/ci.yml
=> Update cachix/install-nix-action to fix failing build CI

apps/dashboard/pages/apply-2023-x/success/index.tsx
=> Add information about application acceptance in success page

apps/dashboard/components/hacker-portal/apps-closed-placeholder.tsx
=> Update apps closed placeholder

apps/dashboard/components/hacker-portal/hacker-portal.tsx, apps/dashboard/components/hackform-tally/hackform-tally.tsx, apps/dashboard/pages/index.tsx
=> Add waitlist for applications

apps/dashboard/pages/apply-2023-x/index.tsx
=> Fix hackform closed when waitlist is open

supabase/migrations/20231018000000_add_application_decision_time.sql
=> Add migration to track application decision time

apps/dashboard/components/hacker-portal/rejection-message.tsx, apps/dashboard/pages/index.tsx
=> Fix RSVP deadline setting, also fix wording

apps/dashboard/components/hacker-portal/rejection-message.tsx, apps/dashboard/components/hacker-portal/rsvp-closed-placeholder.tsx, apps/dashboard/pages/index.tsx
=> Fix RSVP deadline setting (real)

apps/dashboard/pages/index.tsx
=> Fix infinite loading for not admitted users

apps/dashboard/components/hacker-portal/confirmed-placeholder.tsx
=> Fix post-RSVP wording

apps/dashboard/components/rsvp-form/rsvp-form.tsx, libs/env/src/index.ts
=> Remove Discord bot user validation

apps/dashboard/pages/index.tsx
=> Disable RSVP deadline check

apps/dashboard/components/hacker-portal/confirmed-placeholder.tsx, apps/dashboard/components/rsvp-form/rsvp-form.tsx, apps/dashboard/pages/api/discord/[userId].ts, apps/dashboard/repository/discord.repository.ts, supabase/migrations/20231025000000_add_discord_token_table.sql
=> Show discord token in dashboard

apps/sso/components/routeGuard.tsx, apps/sso/middleware.ts, apps/sso/pages/reset-redirect/index.tsx
=> Implement workaroud for password reset

supabase/migrations/20231101000000_add_sponsor_access_events.sql
=> Add sponsor access to tables (fix sponsor portal check in listener)

apps/dashboard/components/identity-portal/check-in-box/check-in-box.tsx, apps/dashboard/layouts/themeless-layout.tsx, supabase/migrations/20231103000000_add_waiver_column.sql
=> Change assign wristband flow to check waiver and discord

apps/dashboard/pages/index.tsx
=> Fix Podium redirect

apps/dashboard/components/hacker-portal/hacker-portal.tsx, apps/dashboard/pages/index.tsx
=> aaaaaaaaaaa

apps/dashboard/pages/sponsor-booth/index.tsx, apps/podium/pages/index.tsx
2. added ADMIN access to podium
- ...
=> 1. added ADMIN access to dashboard/sponsor-booth

apps/dashboard/common/add-event.ts, apps/dashboard/common/calculate-battlepass-progress.ts, apps/dashboard/components/identity-portal/check-in-box/check-in-box.tsx, apps/dashboard/components/identity-portal/scrollable-list-box/scrollable-list-box.tsx, apps/dashboard/components/identity-portal/search-user-box/search-user-box.tsx, apps/dashboard/layouts/themeless-layout.tsx, apps/dashboard/pages/_app.tsx, apps/dashboard/pages/identity-portal/attendee-details-scan/index.tsx, apps/dashboard/pages/identity-portal/attendee-details/index.tsx, apps/dashboard/pages/identity-portal/attendee-event-scan/index.tsx, apps/dashboard/pages/identity-portal/event-checkin/index.tsx, libs/ui-kit-2023/src/lib/checkbox/checkbox.tsx, libs/ui-kit-2023/src/lib/search/search.tsx, package.json, yarn.lock
=> Redesign Identity Portal SCTW/2024
